language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo apt-get install gcc g++ make wget grep sed fswebcam automake autoconf cmake libtool imagemagick libconfig-dev -y
    - mkdir gtest
    - cd gtest
    - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - tar -xf release-1.7.0.tar.gz
    - cd googletest-release-1.7.0
    - cmake -DBUILD_SHARED_LIBS=ON .
    - make -j2
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - cd ../../

script:
    - ./autogen.sh
    - ./configure
    - make -j2 distcheck
