language: c

compiler:
    - clang
    - gcc

before_script:
    sudo apt-get install libgtest-dev libgtest -y

script: ./autogen.sh && ./configure --disable-depscheck --enable-skipsystemctlcalls && sudo make -j2 distcheck
