run_all_tests:
	cd ./abc_brightness_service; \
		MODULE_NAME=abc_brightness_service make -f Makefile -j tests_run

	cd ./abc_power_controller; \
		MODULE_NAME=abc_power_controller make -f Makefile -j tests_run

	cd ./abc_backlight_brightness_controller; \
		MODULE_NAME=abc_backlight_brightness_controller make -f Makefile -j tests_run
