MODULE_NAME = abc_brightness_service

$(MODULE_NAME)_DEPENDENCIES = \
	abc_ambient_brightness_controller \
	abc_backlight_brightness_controller \
	abc_power_controller \
	abc_time_service \
	abc_logging_service \

include Common.mk
